services:
  manbot:
    # 或者 ghcr.io/seepine/manbot:latest
    image: seepine/manbot:latest
    container_name: manbot
    environment:
      - TZ=Asia/Shanghai
      # Tavily API Key，用于 Tavily 搜索服务
      - TAVILY_API_KEY=tvly-xxxxxx
    volumes:
      # manbot_data 替换成你的数据目录
      # --- 由于非root用户，需要手动创建目录并设置权限例如 chmod 777 -R ./manbot_data
      # --- npm 国内源创建 ./manbot_data/.bunfig.toml 文件进行配置
      - ./manbot_data:/data
